# Generated by Django 3.2.3 on 2021-07-10 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reiview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1')),
                ('useful_review', models.IntegerField(blank=True, default=0, null=True, verbose_name='いいね')),
                ('useful_review_record', models.TextField()),
                ('evaluation', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=10, verbose_name='評価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
    ]
