# Generated by Django 3.2.3 on 2021-07-11 02:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_auto_20210710_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reiview',
            new_name='Review',
        ),
    ]
