# Generated by Django 3.2.3 on 2021-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='useful_review_record',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='review',
            name='evaluation',
            field=models.CharField(choices=[('☆☆☆', '☆☆☆：良い'), ('☆☆', '☆☆\u3000：普通'), ('☆', '☆\u3000\u3000：悪い')], max_length=10, verbose_name='評価'),
        ),
    ]
