# Generated by Django 3.2.3 on 2021-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20210711_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='useful_review_record',
            field=models.TextField(null=True),
        ),
    ]
