# Generated by Django 3.2.5 on 2021-07-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_review_useful_review_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='useful_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='useful_review_record',
        ),
    ]
